### ISSUE TITLE
FlexGUI hangs with a M66 wait in a routine

### ISSUE THREAD

**Issue by travis-farmer** [jethornton/flexgui#112]
first documented here: https://forum.linuxcnc.org/40-subroutines-and-ngcgui/54012-possible-bug-with-m66-p26-l4-q7-or-my-use-of-it-or-with-flexgui

i initially thought the bug was in my routine or hardware, and would have been satisfied if it was, as i could fix it. however, the bug does not present itself when i run the machine with Axis instead of FlexGUI.
i watched with HalShow and the pin for my motion.digital-in-XX pin, the actual hardware GPIO pin, changed at just the right moment, so i know it is not a hardware issue.
i removed any din_n_lb labels in FlexGUI associated with the pin to remove conflicts, but the issue persisted.

when M66 is called with a clear pin, it is satisfied, and runs through with no hang.
when M66 is called with a tripped pin that it must wait for, FlexGUI hangs for several seconds, while the routine continues. but when the hang releases, the routine aborts
again, when i run the same test with an Axis GUI, there is no M66 GUI hang, and the routine performs normally.

**Comment by travis-farmer** [comment]
flexgui -> line 205 "self.timer.start(10) # milliseconds"
does a GUI really need updates every 10 milliseconds? i wonder if it is reading too fast and blocking?
when my routine aborts, it acts like M66 failed timeout, even though it passes on the routine.
this afternoon i will change the timer value to slow it down a little and test until and if it becomes stable. just a thought...

**Comment by travis-farmer** [comment]
i tried different values, up to 200ms as well as down to 2ms with no change in the GUI hang.
i was watching closely, and it is not just the M66 that hangs the GUI, but as soon as i call the whole toolchange routine.
my routine is: https://github.com/travis-farmer/linuxcnc/blob/master/nc_files/toolchange.ngc
my M201 remap is: https://github.com/travis-farmer/linuxcnc/blob/master/nc_files/measure.ngc
it still works in Axis, so i doubt the issue is my routine, but there they are, just in case. perhaps though there is something in them that is related to the hang... i too will go through them with a fine tooth comb, see what i flush out, just in case. because i cannot find a direct problem myself with FlexGUI code, other than the hang exists.

**Comment by travis-farmer** [comment]
also to note, when the GUI hangs, only my hardware E-Stop functions. the GUI one, keyboard shortcut, do not. that was a little scary, hunting for one that worked...

**Comment by travis-farmer** [comment]
Some videos, for clarity (i hope).
first, Axis, no spindle run, no hang.
https://www.youtube.com/watch?v=P7NZakCBcrs

second, Axis, with spindle run, no hang (protect ears for spindle brake)
https://www.youtube.com/watch?v=321EB_Zc3sw

third, FlexGUI, no spindle run, with GUI hang, but no machine hang.
https://www.youtube.com/watch?v=rUUzikCsesg

i didn't do a Flex with spindle, because it still hangs, and just doesn't hang enough for an abort. watch the plot movement, or lack thereof, on the flex example. it is not just the plot that hangs, but the whole GUI. no buttons work during a routine. rather surprised Tom-L has not noticed it... unless there is something in my routine causing it somehow. nothing looks out of place to me.
Hope these help describe the situation better.

**Comment by travis-farmer** [comment]
https://forum.linuxcnc.org/48-gladevcp/37933-c-wait-complete
this looks perhaps relevant, as i see it used many times in FlexGUI. not sure how to fix it though...

**Comment by travis-farmer** [comment]
tomorrow, i will test an inconsistency in my testing. on axis, i changed tools via MDI, in flex, i used the tool change buttons. i will use MDI for both and see if it changes anything.

**Comment by travis-farmer** [comment]
allow me to share my thoughts on why i think the inconsistency in testing makes a difference.
the tool change buttons use a lot of .wait_complete(), and those block the python code, as cmorley stated. this blocking is causing the hang in the GUI, but not the machine (the restore of the GUI causes the abort).
I think, if i use MDI rather than tool buttons, it will be executed the same as if it is in the Gcode program i am running. if this passes, we are all set, because i only used the tool change buttons with the spindle turning to test the function. but the buttons are more for setup use, not mid-program use, so NORMALLY, why would i hit a tool change button with the spindle running?
i will also write a Gcode program to test IN PROGRAM use. just some movements around with the spindle running, and tool changes in-between, and see how it performs. that will be the definitive test.
will report back after testing, later this morning. but i suspect we are good.

**Comment by travis-farmer** [comment]
test was a complete success!
using this test Gcode file: https://github.com/travis-farmer/linuxcnc/blob/master/gcode/atc-test.ngc
it does 3 tool changes, 2 while spindle running, and it passed with flying colors!
my test code isn't perfect, as i have a G1 back to the work area, but the gist of it is that it does a few moves, changes tools, does some more moves, changes tools, and does a canned drilling cycle (that i programmed wrong), and then it returns to work home and shuts off the spindle.
ran on latest FlexGUI deb, and LinuxCNC 2.9.3. i updated just before the test, so i proved the code on Axis first to ensure no issues.

what i think is happening, is the tool buttons use of the .wait_complete() causes a little lag in the GUI while it completes the assigned task. this lag exceeded the timeout of my M66 command, and was the issue of my problems.

my recommendations:
for now, a warning that some task buttons may cause a GUI lag that may abort a routine.
for future, read up on what cmorley was talking about on the link above (https://forum.linuxcnc.org/48-gladevcp/37933-c-wait-complete), about putting the commands in a child process, away from the .wait_complete(), so clicking the buttons exit sooner, and don't block the GUI.
I fully understand this will be a PITA, but it is my perspective from what i observed and researched. you can always try it on a single button, and make sure it works first. if no help is achieved, there would not be any benefit to doing it for all like buttons.
my toolchange routine may perhaps just be too complex for the .wait_complete() timeout, but if my thinking is right, it is a good thing my routine flushed out this issue.
i will leave this issue open for now, but if you are satisfied with my results and recommendations, you are welcome to comment and close this issue.

**Comment by jethornton** [comment]
The tool buttons are not used in G code so I'm confused as to how that affects a running G code program.

**Comment by jethornton** [comment]
Ok so you press a tool change button and it runs a remap that takes a long time? I've never used remap so can you provide a simulator config that uses remap say with a G4 P some long time? Maybe I can test with that. The simple-sim would be a good base for the config I think.

**Comment by travis-farmer** [comment]
yes, i can do that, and i will test before i send it to you to verify.

**Comment by travis-farmer** [comment]
ok, i created a sim, and i hope you have unzip on your sim machine...
https://github.com/travis-farmer/linuxcnc/releases/download/sim_for_jt/sim_for_jt.zip
if not, download the source release of your choice, it will be my whole linuxcnc folder, but you can copy the sim from my config directory, to your config directory. it "should" be self-contained.

Directions for test:
a sim Gcode should be preloaded.
close the E-stop, power on, and Home all.
the tool change routine just draws two squares, so the movement of the plot tool shows when it hangs. it also sets tool numbers and tool Z offset. Tool number is displayed above the tool buttons, offset below.
the first square unloads the tool (sets tool 0), and the second square loads the next tool.
DONOT CLICK the tool buttons yet, i want to show what it is supposed to look like first.
Test 1:
run the included Gcode: it will load Tool 1, dwell 3 seconds, load Tool 2, dwell 3 seconds, load Tool 3.
this test should perform normal, without blocking the GUI.

Test 2:
click a tool button, even unload should show it, they all should.
as soon as you click a button, it hangs the GUI, and even the E-stop button is non-functioning. the plot also fails to update, until the tool change routine is complete.

feel free to play with the tools at this point to help illustrate what i am talking about.

I hope that it hangs for you as if not, i don't know what is wrong with my config.

**Comment by jethornton** [comment]
Thanks, I was able to track down the issue using your sim example.
