### ISSUE TITLE
add 'open file'

### ISSUE THREAD

**Issue by Roguish000** [jethornton/flexgui#122]
please add something to open the file specified in the .ini   OPEN_FILE  in the Display section.
right now, if that is in the .ini, it errors with   'file not found'   even with the full path name given.

**Comment by jethornton** [comment]
OPEN_FILE works for me just fine, attach your ini file and I'll check it for errors.

**Comment by Roguish000** [comment]
ok, here's the .ini
![Screenshot at 2024-10-09 08-43-20](https://github.com/user-attachments/assets/c2011a2f-2c66-4669-b95c-00d977636120)
[dd.ini.txt](https://github.com/user-attachments/files/17311082/dd.ini.txt)

**Comment by jethornton** [comment]
Thanks you did choose to use the option that I must have not tested the full path.
