### ISSUE TITLE
Adding extra python logic

### ISSUE THREAD

**Issue by digiexchris** [jethornton/flexgui#172]
Hello! I am amazed! This is such a good project! It saves me a LOT of time. 

Quick question though, I want to add a little bit of code to make some surface grinder usage a little easier that isn't really built in to linuxcnc. I'm basically making a face milling path generator, except that rather than starting from the beginning of the path, it will generate from where the current position is and continue as if it had been stopped mid-program. Basically emulating the old hydraulic semi-auto surface grinders. I'm speceifying X axis start and end, infeed start and end, downfeed start and end, and then hitting start. I can turn off infeed by deselecting one button, or have it stop infeeding at the max limit dynamically, rather than having to edit the gcode program.

Attached is an image with my current UI:
![image](https://github.com/user-attachments/assets/9f12c4a0-4806-4a88-b35c-b94c2dc55f9e)

And the code that backs it:
https://github.com/digiexchris/qtpyvcp_grinder_touch/blob/main/src/grinder_touch/mainwindow.py

This works, but depends on the UI thread doing a lot of the work so the stop and start of the traverse actions are not that consistent, so I'm going to switch it to generated gcode or maybe a queue of MDI commands instead.

I have it working on an older version of mill_touch linked from the qtpyvcp page, but then I discovered flexgui, and that solves a lot of problems for me. Except, I need to write some handlers for some controls myself. 

Do you have a way to inject python along with the .ui, or will I have to fork and build flexgui instead? Or, am I over thinking this, and there's a better way to do this?

**Comment by jethornton** [comment]
I need a simple example of what you need to understand. I don't see why flex can't import another python file it does that now for resources.py and that's added in the ini file.

I assume you want to connect some buttons to python code?

JT

**Comment by digiexchris** [comment]
That's exactly it, I want to connect some buttons to custom python code. I forgot that it imported resources.py, I think that may actually be what I need!

And the more I think about how to communicate what I'm doing, the more I suspect I'm trying to do things the hard way with the grinder automation. I need to look into subroutines more. If I can make a subroutine that repeat forever making passes back and forth with a Y movement at the end of each X movement, that sounds better. 

The challenge I had in the past trying that entirely in G/M/O code was the extra options, like a Y movement only at the max_x position of the X movement, but not at the min_x,depending on if that option was selected. or having the variables in the routine update dynamically from things entered into the UI if they changed without having to stop and regenerate the program. That's not that big of a burden though, if I have to stop to update params and start again.

I'm a programmer, though inexperienced at python and gcode subroutines, so I automatically gravitated to doing automation through python in the UI but it's probably not the best idea anyway given the ui thread update speed.

**Comment by jethornton** [comment]
Well to connect a button to a function you have to make that connection in an init or something. Let me putz with that in the morning now that I know what you need. Thinking out loud an ini entry with python file name and the startup function might work.

JT

**Comment by digiexchris** [comment]
yes that sounds ideal, thanks!

**Comment by jethornton** [comment]
I believe I have it sorted out.
https://gnipsel.com/linuxcnc/flexgui/misc.html#import-python

JT

**Comment by digiexchris** [comment]
That's perfect! Thanks again, you've saved me countless hours of work with flexgui

**Comment by digiexchris** [comment]
just trying this out now. I get an error that it can't find my module, which I think is due to errors in my code, but it seems there is a try/except block wrapping the loading of the imported module, so any errors are squashed. Is there a way to see the errors or test the py without flexgui somehow? Or, can the try/except block be configured via INI so it can be disabled for dev and crash with a stack trace as normal?

**Comment by jethornton** [comment]
I added a print statement to print out the error when you run linuxcnc from a terminal

JT
