### ISSUE TITLE
versioning suggestion

### ISSUE THREAD

**Issue by digiexchris** [jethornton/flexgui#213]
I have a small suggestion on workflow that has had stability benefits in other projects with respects to tags to version numbers.

Have 3 main branches, master release-candidate, and dev. Master is considered the stable branch, and tags reference master commits.

Development happens on dev, or branches off of dev which are then merged into dev. I don't normally suggest release-candidate for projects like this, except it makes automation easier for you if you want to setup automatic semver versioning. Infact, you could probably eliminate the dev branch and just branch off of the release-candidate if that makes more sense to you.

If versioning also follows semver, Major.Minor.Patch (ie 1.0.3 means major version 1, minor 0, and 3 patch merges have occurred), and a debian package matches that commit, then a user can be sure that their software version is up to date with a particular tag.Looking back at your previous version bumps, I would consider us at 1.3.0, since you have had 3 releases that you mentioned in the forums. I'd reserve the last digit for bug fixes or other minor things.

Once dev is considered good, or at some other point you decide, it is merged into release-candidate. When release-candidate is merged into master, master is tagged with the next release version (1.1.0). If a bugfix needs to be applied to master directly, the patch version increments.

There are a few benefits to this:
1: apt automatically upgrades to newer versions without requiring --reinstall added on, and I can determine at a glance if I have the latest version or not
2: in the github releases page, the debian package matches the source tarball attached to that version, and it matches the git sha of that tag
3: you could make a free github organization which includes up to 2000 free CI/CD minutes per month, meaning a debian package could be automatically created and tagging could be done automatically for every merge from release-candidate to master. 

Just a thought. Might be useful as usage grows, but feel free to close this issue

**Comment by jethornton** [comment]
Thanks for taking the time to make the suggestion.

Most of the suggestions sound like it would increase the complexity of the project and it's not in a debian repo so apt could not update it. The user has to download a deb and install it with gdebi or similar.

In the past I've had issues with branches and merging so I try and stay away from that.

The benefits I really don't understand them.
1 the deb is manually installed by user so apt has no clue about the latest version AFAIK
2 I think that all matches now but not sure
3 Not sure what that means.

I'm nearly complete with this project so soon it would only be bug fixes AFAIK.

JT
